# Generated by Django 5.2.2 on 2025-11-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='custdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(default='', max_length=128)),
                ('confirmPassword', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
