# Generated by Django 5.2.2 on 2025-11-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0002_custdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custdata',
            name='confirmPassword',
        ),
        migrations.AlterField(
            model_name='custdata',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='custdata',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
