# Generated by Django 5.2.2 on 2025-11-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0003_remove_custdata_confirmpassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custdata',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
